### ISSUE TITLE
Каждый ответ регистируется дважды

### ISSUE THREAD

**Issue by adidvar** [fkwa/naurok-solver#1]
Незнаю как но при использовании
"Php index.php -T 30 -C <code> --name =" <name> "--mistakes = 2" у меня результат в тесте вышел 150/100

**Comment by celestora** [comment]
А какой тест был?
Есть логи (вывод программы)?

**Comment by adidvar** [comment]
Обычный тест на 12 вопросов. Повторил несколько раз на своем тесте удалось получить 200% баллов. Логи:

[user@OLD naurok-solver]$ php index.php -T 1 -C 922390 --name="someonejony" --mistakes=1 --vvv
[Wed, 15 Apr 2020 17:25:18 +0000] [DEBUG] — Acquiring CSRF token: done (tok = 'PcUL2iXamXkdzISGqZkg52Gfaay_AVoRnt7hQ90iMKtNhjmjbKPhNUj-8d7D9naJOOgklNBjDGDkrK8qlX0B8g=='
[Wed, 15 Apr 2020 17:25:18 +0000] [INFO] — Trying to log in as someonejony to lobby №922390
[Wed, 15 Apr 2020 17:25:18 +0000] [DEBUG] — Acquiring session id: done (sess = '17469310')
[Wed, 15 Apr 2020 17:25:19 +0000] [INFO] — Successfully logged in, trying to load answers...
[Wed, 15 Apr 2020 17:25:19 +0000] [DEBUG] — Session GUID = 559531b4-2c28-4b9b-8628-fe7148690e56
[Wed, 15 Apr 2020 17:25:19 +0000] [INFO] — Attempting to answer question
[Wed, 15 Apr 2020 17:25:19 +0000] [INFO] — Submitting answers...
[Wed, 15 Apr 2020 17:25:20 +0000] [SUCC] — Response from server: Відмінно!
[Wed, 15 Apr 2020 17:25:21 +0000] [INFO] — Attempting to answer question
[Wed, 15 Apr 2020 17:25:21 +0000] [INFO] — Submitting answers...
[Wed, 15 Apr 2020 17:25:21 +0000] [SUCC] — Response from server: Так тримати!
[Wed, 15 Apr 2020 17:25:22 +0000] [INFO] — Attempting to answer question
[Wed, 15 Apr 2020 17:25:22 +0000] [INFO] — Submitting answers...
[Wed, 15 Apr 2020 17:25:22 +0000] [SUCC] — Response from server: Молодець!
[Wed, 15 Apr 2020 17:25:23 +0000] [INFO] — Attempting to answer question
[Wed, 15 Apr 2020 17:25:23 +0000] [INFO] — Submitting answers...
[Wed, 15 Apr 2020 17:25:24 +0000] [SUCC] — Response from server: Молодець!
[Wed, 15 Apr 2020 17:25:25 +0000] [INFO] — Attempting to answer question
[Wed, 15 Apr 2020 17:25:25 +0000] [INFO] — Submitting answers...
[Wed, 15 Apr 2020 17:25:25 +0000] [SUCC] — Response from server: Відмінно!
[Wed, 15 Apr 2020 17:25:26 +0000] [INFO] — Attempting to answer question
[Wed, 15 Apr 2020 17:25:26 +0000] [INFO] — Submitting answers...
[Wed, 15 Apr 2020 17:25:27 +0000] [SUCC] — Response from server: Так тримати!
[Wed, 15 Apr 2020 17:25:28 +0000] [INFO] — Attempting to answer question
[Wed, 15 Apr 2020 17:25:28 +0000] [INFO] — Submitting answers...
[Wed, 15 Apr 2020 17:25:28 +0000] [SUCC] — Response from server: Добре!
[Wed, 15 Apr 2020 17:25:29 +0000] [INFO] — Attempting to answer question
[Wed, 15 Apr 2020 17:25:29 +0000] [INFO] — Submitting answers...
[Wed, 15 Apr 2020 17:25:29 +0000] [SUCC] — Response from server: Чудово!
[Wed, 15 Apr 2020 17:25:30 +0000] [INFO] — Attempting to answer question
[Wed, 15 Apr 2020 17:25:30 +0000] [INFO] — Submitting answers...
[Wed, 15 Apr 2020 17:25:31 +0000] [SUCC] — Response from server: Правильно!
[Wed, 15 Apr 2020 17:25:32 +0000] [INFO] — Attempting to answer question
[Wed, 15 Apr 2020 17:25:32 +0000] [INFO] — Submitting answers...
[Wed, 15 Apr 2020 17:25:32 +0000] [SUCC] — Response from server: Чудово!
[Wed, 15 Apr 2020 17:25:33 +0000] [INFO] — Attempting to answer question
[Wed, 15 Apr 2020 17:25:33 +0000] [INFO] — Submitting answers...
[Wed, 15 Apr 2020 17:25:33 +0000] [SUCC] — Response from server: Так тримати!
[Wed, 15 Apr 2020 17:25:34 +0000] [INFO] — Attempting to answer question
[Wed, 15 Apr 2020 17:25:34 +0000] [INFO] — This question will be answered incorrectly, because of settings
PHP Notice:  Undefined property: stdClass::$message_scene in /home/user/Naurok/naurok-solver/index.php on line 215
[Wed, 15 Apr 2020 17:25:35 +0000] [SUCC] — Response from server: Виникла внутрішня помилка сервера.
[Wed, 15 Apr 2020 17:25:36 +0000] [INFO] — Answered all questions
[Wed, 15 Apr 2020 17:25:36 +0000] [INFO] — Closing session
[Wed, 15 Apr 2020 17:25:36 +0000] [SUCC] — Session closed sucessfully: https://naurok.com.ua/test/complete/559531b4-2c28-4b9b-8628-fe7148690e56

**Comment by celestora** [comment]
![image](https://user-images.githubusercontent.com/34442450/79442748-a15fca00-7fe1-11ea-87f8-e4547a677505.png)
Возможно, это связано с тем, что неправильные ответы формируются.. неправильно.

**Comment by adidvar** [comment]
Интересный факт если отправлять 6 неправильных ответов то оно регистрирует 12 корректных 12 некорректных и так всегда:

ошибки: 3 18/6
ошибки: 2 20/4
ошибки: 0 24/0
ошибки: 6 12/12

При этом программа всегда делает 12 запросов. А API регистрирует каждый запрос как два ответа .Мне кажется, что там есть подвох в Апи.

**Comment by celestora** [comment]
> Мне кажется, что там есть подвох в Апи.

А мне кажется что апи кривой просто 😳, иначе давалась бы ошибка понятнее чем "Виникла внутрішня помилка сервера."

**Comment by adidvar** [comment]
Кривое не кривой, а сайт с ним работает нормально.

**Comment by adidvar** [comment]
Кривой сайт для кривого API.

**Comment by celestora** [comment]
Проблема этого API в том, что клиент может делать то, чем по идее должен заниматься сервер. \
Причина этого бага, собственно, оказалась проста - параметр point метода test.responses.answer указывает сколько баллов нужно дать за ответ. Вот только зачем это добавили в API не понятно) \
Зато понятно теперь зачем этот параметр нужен, щас пофиксим.
