### ISSUE TITLE
Добрый, вылетает скрипт

### ISSUE THREAD

**Issue by mykden** [fkwa/naurok-solver#3]
mikhail@mikhail-pc:~/Загрузки/php-7.4.5/naurok-solver$ php index.php -C 144644 -T 10 --name="Andrey" --mistakes=4

PHP Fatal error:  Uncaught Error: Call to undefined function curl_init() in /home/mikhail/Загрузки/php-7.4.5/naurok-solver/index.php:71
Stack trace:
#0 /home/mikhail/Загрузки/php-7.4.5/naurok-solver/index.php(138): http('GET', 'https://naurok....')
#1 /home/mikhail/Загрузки/php-7.4.5/naurok-solver/index.php(199): startTest(144644, 'Andrey')
#2 /home/mikhail/Загрузки/php-7.4.5/naurok-solver/index.php(232): main(7, Array)
#3 {main}
  thrown in /home/mikhail/Загрузки/php-7.4.5/naurok-solver/index.php on line 71

P.S хочу запустить со своей машины т.к наш препод может по IP чекать

**Comment by Qupipab** [comment]
Точь в точь такая же проблема

**Comment by ivhorodko** [comment]
> mikhail@mikhail-pc:~/Загрузки/php-7.4.5/naurok-solver$ php index.php -C 144644 -T 10 --name="Andrey" --mistakes=4
> 
> PHP Fatal error: Uncaught Error: Call to undefined function curl_init() in /home/mikhail/Загрузки/php-7.4.5/naurok-solver/index.php:71
> Stack trace:
> #0 /home/mikhail/Загрузки/php-7.4.5/naurok-solver/index.php(138): http('GET', 'https://naurok....')
> #1 /home/mikhail/Загрузки/php-7.4.5/naurok-solver/index.php(199): startTest(144644, 'Andrey')
> #2 /home/mikhail/Загрузки/php-7.4.5/naurok-solver/index.php(232): main(7, Array)
> #3 {main}
> thrown in /home/mikhail/Загрузки/php-7.4.5/naurok-solver/index.php on line 71
> 
> P.S хочу запустить со своей машины т.к наш препод может по IP чекать

В вашей папке с php 7.4 файлик php.ini-production > переименовываете в php.ini >
В этом файле нужно раскомментировать 914 строку "extension=curl", тем самым вы подключите библеотеку curl о которой указано в ошибке, и которую автор просит подключить.

**Comment by ivhorodko** [comment]
Новая ошибка, не пойму, что делаю не так, extension=openssl раскоментил.
Unexpected request error: SSL certificate problem: unable to get local issuer certificate

**Comment by ivhorodko** [comment]
$ch = curl_init();
Добавил вот эту строку > curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);

Теперь 
[INFO] — Trying to log in as Амелия Понд to lobby №913093
[FATAL] — Session cannot be initiated. Please check your code.

**Comment by mykden** [comment]
Итак, файл переименовал, раскоментировал, переименовал обратно на php.ini-production (как оказалось, можно обойтись без переименования, просто открыть через текстовый редактор)
в index.php добавил 2 строчки (которые упомянуты выше)
теперь новая ошибка

Fatal error: Uncaught Error: Call to undefined function curl_init() in C:\naurok\index.php:71
Stack trace:
#0 C:\naurok\index.php(139): http('GET', 'https://naurok....')
#1 C:\naurok\index.php(200): startTest(882663, '\xD0\x90\xD0\xBD\xD0\xB4\xD1\x80\xD0\xB5\xD0\xB9')
#2 C:\naurok\index.php(233): main(6, Array)
#3 {main}
  thrown in C:\naurok\index.php on line 71

 Насколько я понял, он не может определить функцию curl_init

![image](https://user-images.githubusercontent.com/30213962/80704507-59669a00-8aed-11ea-9b47-e202ba12588c.png)

![image](https://user-images.githubusercontent.com/30213962/80704575-8155fd80-8aed-11ea-9204-caf95a2bb706.png)

**Comment by mykden** [comment]
Странно, на Ubuntu 19.10 сразу все заработало, вопрос закрыт, спасибо)
