### ISSUE TITLE
Не может определить ответы

### ISSUE THREAD

**Issue by mykden** [fkwa/naurok-solver#4]
mikhail@mikhail-pc:~$ php index.php -C 882664 -T 5 --name="TEST" --mistakes=4
[Thu, 30 Apr 2020 15:57:23 +0300] [INFO] — Trying to log in as TEST to lobby №882664
[Thu, 30 Apr 2020 15:57:23 +0300] [INFO] — Successfully logged in, trying to load answers...
[Thu, 30 Apr 2020 15:57:23 +0300] [FATAL] — Could not fetch answers
 
В это же время телеграм бот справляется на ура

**Comment by celestora** [comment]
Telegram-бот имеет слегка другой код. А этот уже не актуален :<

**Comment by mykden** [comment]
А исходник выложишь?)

**Comment by dimutch833** [comment]
Да я сейчас попитался запустить видало ошибку

**Comment by mykden** [comment]
Бот в телеге делает просто на 0 баллов

**Comment by celestora** [comment]
> Бот в телеге делает просто на 0 баллов

naurok не регистрируют ответы с подозрительных IP.
