### ISSUE TITLE
Fetch answers error

### ISSUE THREAD

**Issue by ih3xcode** [fkwa/naurok-solver#6]
PHP Notice:  Constant MISTAKES already defined in C:\php\index.php on line 33
[Sun, 03 May 2020 11:42:00 +0000] [INFO] — Trying to log in as Амелия Понд to lobby №886638
[Sun, 03 May 2020 11:42:00 +0000] [INFO] — Successfully logged in, trying to load answers...
[Sun, 03 May 2020 11:42:00 +0000] [FATAL] — Could not fetch answers

**Comment by JustiFox** [comment]
Скрипт пофикшен
